
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace editor.cfg.test
{

public abstract class Shape :  Luban.EditorBeanBase 
{
    public Shape()
    {
    }
    public abstract string GetTypeStr();

    private int _typeIndex = -1;
    private int TypeIndex => _typeIndex;
    private static string[] Types = new string[]
    {
        "Circle",
        "test2.Rectangle",
    };
    private static string[] TypeAlias = new string[]
    {
        "圆",
        "矩形",
    };

    public static Shape Create(string type)
    {
        switch (type)
        {
            case "test.Circle":   
            case "Circle":
            {
                var obj = new test.Circle();
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "test2.Rectangle":
            {
                var obj = new test2.Rectangle();
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            default: return null;
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderShape(ref Shape obj)
    {
        UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
        var array = ConfigEditorSettings.showComment ? TypeAlias : Types;
        UnityEditor.EditorGUILayout.BeginHorizontal();
        UnityEditor.EditorGUILayout.LabelField("类型", GUILayout.Width(100));
        var index = UnityEditor.EditorGUILayout.Popup(obj.TypeIndex, array, GUILayout.Width(200));
        if (obj.TypeIndex != index)
        {
            obj = Create(Types[index]);
        }
        UnityEditor.EditorGUILayout.EndHorizontal();
        obj?.Render();
        UnityEditor.EditorGUILayout.EndVertical();
    }

    public override void Render()
    {
    }
    public static Shape LoadJsonShape(SimpleJSON.JSONNode _json)
    {
        string type = _json["$type"];
        Shape obj;
        switch (type)
        {
            case "test.Circle":   
            case "Circle":
            {
                obj = new test.Circle(); 
                obj._typeIndex = Array.IndexOf(Types, "Circle");
                break;
            }
            case "test2.Rectangle":
            {
                obj = new test2.Rectangle(); 
                obj._typeIndex = Array.IndexOf(Types, "test2.Rectangle");
                break;
            }
            default: throw new SerializationException();
        }
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonShape(Shape _obj, SimpleJSON.JSONNode _json)
    {
        _json["$type"] = _obj.GetTypeStr();
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }


    public override string ToString()
    {
        return "{ "
        + "}";
    }
}

}

