
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;
using System;

namespace editor.cfg.ai
{

public abstract class Service :  ai.Node 
{
    public Service(Action<Luban.EditorBeanBase> setChangeAction = null)  : base(setChangeAction) 
    {
        _setChangeAction = setChangeAction;
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "Service";

    private int _typeIndex = -1;
    public new int TypeIndex
    {
        get => _typeIndex;
        set
        {
            if(_typeIndex == value)
            {
                return;
            }
            _typeIndex = value;
            var obj = Create(Types[value], _setChangeAction);
            _setChangeAction(obj);
        }
    }
    private new static string[] Types = new string[]
    {
        "UeSetDefaultFocus",
        "ExecuteTimeStatistic",
        "ChooseTarget",
        "KeepFaceTarget",
        "GetOwnerPlayer",
        "UpdateDailyBehaviorProps",
    };
    private new static string[] TypeAlias = new string[]
    {
        "UeSetDefaultFocus",
        "ExecuteTimeStatistic",
        "ChooseTarget",
        "KeepFaceTarget",
        "GetOwnerPlayer",
        "UpdateDailyBehaviorProps",
    };

    public new static Service Create(string type, Action<Luban.EditorBeanBase> setChangeAction)
    {
        switch (type)
        {
            case "ai.UeSetDefaultFocus":   
            case "UeSetDefaultFocus":
            {
                var obj = new ai.UeSetDefaultFocus(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "ai.ExecuteTimeStatistic":   
            case "ExecuteTimeStatistic":
            {
                var obj = new ai.ExecuteTimeStatistic(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "ai.ChooseTarget":   
            case "ChooseTarget":
            {
                var obj = new ai.ChooseTarget(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "ai.KeepFaceTarget":   
            case "KeepFaceTarget":
            {
                var obj = new ai.KeepFaceTarget(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "ai.GetOwnerPlayer":   
            case "GetOwnerPlayer":
            {
                var obj = new ai.GetOwnerPlayer(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            case "ai.UpdateDailyBehaviorProps":   
            case "UpdateDailyBehaviorProps":
            {
                var obj = new ai.UpdateDailyBehaviorProps(setChangeAction);
                obj._typeIndex = Array.IndexOf(Types,type);
                return obj;
            }
            default: return null;
        }
    }

    private static GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public static void RenderService(Service obj)
    {
        UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
        var array = ConfigEditorSettings.showComment ? TypeAlias : Types;
        UnityEditor.EditorGUILayout.BeginHorizontal();
        UnityEditor.EditorGUILayout.LabelField("类型", GUILayout.Width(100));
        obj.TypeIndex = UnityEditor.EditorGUILayout.Popup(obj.TypeIndex, array, GUILayout.Width(200));
        UnityEditor.EditorGUILayout.EndHorizontal();
        obj?.Render();
        UnityEditor.EditorGUILayout.EndVertical();
    }

    public override void Render()
    {
{
    ai.Service.RenderService(this);
}    }
    public static Service LoadJsonService(SimpleJSON.JSONNode _json, Action<Luban.EditorBeanBase> setChangeAction = null)
    {
        string type = _json["$type"];
        Service obj;
        switch (type)
        {
            case "ai.UeSetDefaultFocus":   
            case "UeSetDefaultFocus":
            {
                obj = new ai.UeSetDefaultFocus(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "UeSetDefaultFocus");
                break;
            }
            case "ai.ExecuteTimeStatistic":   
            case "ExecuteTimeStatistic":
            {
                obj = new ai.ExecuteTimeStatistic(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "ExecuteTimeStatistic");
                break;
            }
            case "ai.ChooseTarget":   
            case "ChooseTarget":
            {
                obj = new ai.ChooseTarget(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "ChooseTarget");
                break;
            }
            case "ai.KeepFaceTarget":   
            case "KeepFaceTarget":
            {
                obj = new ai.KeepFaceTarget(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "KeepFaceTarget");
                break;
            }
            case "ai.GetOwnerPlayer":   
            case "GetOwnerPlayer":
            {
                obj = new ai.GetOwnerPlayer(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "GetOwnerPlayer");
                break;
            }
            case "ai.UpdateDailyBehaviorProps":   
            case "UpdateDailyBehaviorProps":
            {
                obj = new ai.UpdateDailyBehaviorProps(setChangeAction); 
                obj._typeIndex = Array.IndexOf(Types, "UpdateDailyBehaviorProps");
                break;
            }
            default: throw new SerializationException();
        }
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonService(Service _obj, SimpleJSON.JSONNode _json)
    {
        _json["$type"] = _obj.GetTypeStr();
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }


    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nodeName:" + nodeName + ","
        + "}";
    }
}

}

