
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;
using UnityEngine;
using System.Linq;

namespace editor.cfg.ai
{

public abstract class Task :  ai.FlowNode 
{
    public Task()
    {
    }
    public override string GetTypeStr() => TYPE_STR;
    private const string TYPE_STR = "ai.Task";

    private int _typeIndex = -1;
    public new int TypeIndex
    {
        get => _typeIndex;
        set
        {
            if(_typeIndex == value)
            {
                return;
            }
            _typeIndex = value;
            Instance = Create(Types[value]);
        }
    }
    public new Task Instance { get; set;}
    public new static List<string> Types = new List<string>()
    {
        "ai.UeWait",
        "ai.UeWaitBlackboardTime",
        "ai.MoveToTarget",
        "ai.ChooseSkill",
        "ai.MoveToRandomLocation",
        "ai.MoveToLocation",
        "ai.DebugPrint",
    };

    public new static Task Create(string type)
    {
        switch (type)
        {
            case "ai.UeWait":   
            case "UeWait":return new ai.UeWait();
            case "ai.UeWaitBlackboardTime":   
            case "UeWaitBlackboardTime":return new ai.UeWaitBlackboardTime();
            case "ai.MoveToTarget":   
            case "MoveToTarget":return new ai.MoveToTarget();
            case "ai.ChooseSkill":   
            case "ChooseSkill":return new ai.ChooseSkill();
            case "ai.MoveToRandomLocation":   
            case "MoveToRandomLocation":return new ai.MoveToRandomLocation();
            case "ai.MoveToLocation":   
            case "MoveToLocation":return new ai.MoveToLocation();
            case "ai.DebugPrint":   
            case "DebugPrint":return new ai.DebugPrint();
            default: return null;
        }
    }

    private GUIStyle _areaStyle = new GUIStyle(GUI.skin.button);

    public override void Render()
    {
{
    var __list0 = ai.Task.Types.Select(t => new GUIContent(t)).ToArray();
    UnityEditor.EditorGUILayout.BeginVertical(_areaStyle);
    if (this == null)
    {
        
        this.TypeIndex = 0;
    }
    UnityEditor.EditorGUILayout.BeginHorizontal();
    UnityEditor.EditorGUILayout.LabelField("类型", GUILayout.Width(100));
    this.TypeIndex = UnityEditor.EditorGUILayout.Popup(this.TypeIndex, __list0, GUILayout.Width(200));
    UnityEditor.EditorGUILayout.EndHorizontal();
    this.Instance.Render();
    UnityEditor.EditorGUILayout.EndVertical();
}    }

    public static Task LoadJsonTask(SimpleJSON.JSONNode _json)
    {
        string type = _json["$type"];
        Task obj;
        switch (type)
        {
            case "ai.UeWait":   
            case "UeWait":obj = new ai.UeWait(); break;
            case "ai.UeWaitBlackboardTime":   
            case "UeWaitBlackboardTime":obj = new ai.UeWaitBlackboardTime(); break;
            case "ai.MoveToTarget":   
            case "MoveToTarget":obj = new ai.MoveToTarget(); break;
            case "ai.ChooseSkill":   
            case "ChooseSkill":obj = new ai.ChooseSkill(); break;
            case "ai.MoveToRandomLocation":   
            case "MoveToRandomLocation":obj = new ai.MoveToRandomLocation(); break;
            case "ai.MoveToLocation":   
            case "MoveToLocation":obj = new ai.MoveToLocation(); break;
            case "ai.DebugPrint":   
            case "DebugPrint":obj = new ai.DebugPrint(); break;
            default: throw new SerializationException();
        }
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonTask(Task _obj, SimpleJSON.JSONNode _json)
    {
        _json["$type"] = _obj.Instance.GetTypeStr();
        _obj.Instance.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public bool ignoreRestartSelf;

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "nodeName:" + nodeName + ","
        + "decorators:" + Luban.StringUtil.CollectionToString(decorators) + ","
        + "services:" + Luban.StringUtil.CollectionToString(services) + ","
        + "ignoreRestartSelf:" + ignoreRestartSelf + ","
        + "}";
    }
}

}

